name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./
          libraries: |
            # The "blink" sketch being compiled in this demo doesn't use any libraries, so just use an empty list
            - source-url: https://github.com/adafruit/Adafruit_BusIO/archive/refs/tags/1.15.0.zip
            - source-url: https://github.com/adafruit/Adafruit_FT6206_Library/archive/refs/tags/1.1.0.zip
            - source-url: https://github.com/adafruit/Adafruit-GFX-Library/archive/refs/tags/1.11.9.zip
            - source-url: https://github.com/adafruit/Adafruit_ILI9341/archive/refs/tags/1.6.0.zip
            - source-url: https://github.com/adafruit/Adafruit_TouchScreen/archive/refs/tags/1.1.5.zip
              
